"""Tests for scripts/check_architecture.py."""

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts import check_architecture  # noqa: E402


@pytest.fixture(scope="module")
def architecture_module():
    return check_architecture


def test_collect_violations_passes_on_repository(architecture_module) -> None:
    violations = architecture_module.collect_violations(write_project_map=False)
    assert violations == []


def test_generated_project_map_section_lists_groups(architecture_module) -> None:
    generated = architecture_module._generated_project_map_section()
    assert "tests:tui" in generated
    assert "tests:rest" in generated
    assert "Generated by `scripts/check_architecture.py`" in generated


def test_replace_generated_section_is_idempotent(architecture_module, tmp_path: Path) -> None:
    content = "\n".join(
        [
            "# Project map",
            "[project-map:start]",
            "old",
            "[project-map:end]",
            "",
        ]
    )
    generated = "new\n"
    once = architecture_module._replace_generated_section(content, generated)
    twice = architecture_module._replace_generated_section(once, generated)
    assert once == twice


def test_module_import_hits_detects_banned_import(architecture_module, tmp_path: Path) -> None:
    path = tmp_path / "sample.py"
    path.write_text("import argparse\n", encoding="utf-8")
    hits = architecture_module._module_import_hits(path, ("argparse",))
    assert hits == ["import argparse"]


def test_application_parent_package_import_is_flagged(architecture_module, tmp_path: Path) -> None:
    path = tmp_path / "inspection.py"
    path.write_text(
        "from ...application.project_resolution import resolve_project_wordlist\n",
        encoding="utf-8",
    )
    hits = architecture_module._application_parent_package_import_hits(path)
    assert hits == ["from ...application.project_resolution"]


def test_event_ids_are_unique(architecture_module) -> None:
    assert architecture_module._check_event_ids() == []


def test_main_check_success(architecture_module, capsys) -> None:
    assert architecture_module.main(["--check"]) == 0
    assert "ARCHITECTURE_VALIDATION=success" in capsys.readouterr().out


def test_resolved_application_import_hits_relative(architecture_module, tmp_path: Path) -> None:
    package = tmp_path / "spell_sync" / "core_like"
    package.mkdir(parents=True)
    (tmp_path / "spell_sync" / "__init__.py").write_text("", encoding="utf-8")
    (package / "__init__.py").write_text("", encoding="utf-8")
    path = package / "sample.py"
    path.write_text("from ..application.reports import X\n", encoding="utf-8")
    original_root = architecture_module.ROOT
    architecture_module.ROOT = tmp_path
    try:
        hits = architecture_module._resolved_application_import_hits(path)
    finally:
        architecture_module.ROOT = original_root
    assert hits
    assert any("spell_sync.application.reports" in hit for hit in hits)


def test_resolved_application_import_skips_type_checking(
    architecture_module, tmp_path: Path
) -> None:
    package = tmp_path / "spell_sync" / "core_like"
    package.mkdir(parents=True)
    (tmp_path / "spell_sync" / "__init__.py").write_text("", encoding="utf-8")
    (package / "__init__.py").write_text("", encoding="utf-8")
    path = package / "sample.py"
    path.write_text(
        "from typing import TYPE_CHECKING\n"
        "if TYPE_CHECKING:\n"
        "    from ..application.reports import X\n",
        encoding="utf-8",
    )
    original_root = architecture_module.ROOT
    architecture_module.ROOT = tmp_path
    try:
        hits = architecture_module._resolved_application_import_hits(path)
    finally:
        architecture_module.ROOT = original_root
    assert hits == []


def test_core_import_of_application_is_flagged(architecture_module, tmp_path: Path) -> None:
    spell_sync = tmp_path / "spell_sync"
    spell_sync.mkdir()
    (spell_sync / "__init__.py").write_text("", encoding="utf-8")
    offender = spell_sync / "sync_run.py"
    offender.write_text("from .application.reports import X\n", encoding="utf-8")
    original_root = architecture_module.ROOT
    architecture_module.ROOT = tmp_path
    try:
        violations = architecture_module._check_core_does_not_import_application()
    finally:
        architecture_module.ROOT = original_root
    assert any(item.check_id.endswith("DEP-001") for item in violations)


def test_uses_contextvar_detects_import(architecture_module, tmp_path: Path) -> None:
    path = tmp_path / "sample.py"
    path.write_text("from contextvars import ContextVar\n", encoding="utf-8")
    assert architecture_module._uses_contextvar(path) is True


def test_stale_generated_section_reports_violation(architecture_module, tmp_path: Path) -> None:
    project_map = tmp_path / "PROJECT_MAP.md"
    project_map.write_text(
        "\n".join(
            [
                "# Project map",
                "## Entry points",
                "## Layers and allowed dependencies",
                "## Application requests",
                "## Services",
                "## Core mutation modules",
                "## Diagnostics and history",
                "## TUI flows",
                "## Target discovery",
                "## Package resources",
                "## Test suites by responsibility",
                "[project-map:start]",
                "stale",
                "[project-map:end]",
                "## Common change recipes",
            ]
        ),
        encoding="utf-8",
    )
    violations = architecture_module._check_project_map(write=False, project_map=project_map)
    assert any(item.check_id.endswith("MAP-004") for item in violations)
