"""Tests for scripts/check-architecture.py."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "check-architecture.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("check_architecture", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["check_architecture"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def architecture_module():
    return _load_module()


def test_collect_violations_passes_on_repository(architecture_module) -> None:
    violations = architecture_module.collect_violations(write_project_map=False)
    assert violations == []


def test_generated_project_map_section_lists_groups(architecture_module) -> None:
    generated = architecture_module._generated_project_map_section()
    assert "tests.tui" in generated
    assert "tests.core" in generated
    assert "Generated by `scripts/check-architecture.py`" in generated


def test_replace_generated_section_is_idempotent(architecture_module, tmp_path: Path) -> None:
    content = "\n".join(
        [
            "# Project map",
            "[project-map:start]",
            "old",
            "[project-map:end]",
            "",
        ]
    )
    generated = "new\n"
    once = architecture_module._replace_generated_section(content, generated)
    twice = architecture_module._replace_generated_section(once, generated)
    assert once == twice


def test_module_import_hits_detects_banned_import(architecture_module, tmp_path: Path) -> None:
    path = tmp_path / "sample.py"
    path.write_text("import argparse\n", encoding="utf-8")
    hits = architecture_module._module_import_hits(path, ("argparse",))
    assert hits == ["import argparse"]


def test_event_ids_are_unique(architecture_module) -> None:
    assert architecture_module._check_event_ids() == []


def test_main_check_success(architecture_module, capsys) -> None:
    assert architecture_module.main(["--check"]) == 0
    assert "ARCHITECTURE_VALIDATION=success" in capsys.readouterr().out


def test_stale_generated_section_reports_violation(architecture_module, tmp_path: Path) -> None:
    project_map = tmp_path / "PROJECT_MAP.md"
    project_map.write_text(
        "\n".join(
            [
                "# Project map",
                "## Entry points",
                "## Layers and allowed dependencies",
                "## Application requests",
                "## Services",
                "## Core mutation modules",
                "## Diagnostics and history",
                "## TUI flows",
                "## Target discovery",
                "## Package resources",
                "## Test suites by responsibility",
                "[project-map:start]",
                "stale",
                "[project-map:end]",
                "## Common change recipes",
            ]
        ),
        encoding="utf-8",
    )
    original = architecture_module.PROJECT_MAP_PATH
    architecture_module.PROJECT_MAP_PATH = project_map
    try:
        violations = architecture_module._check_project_map(write=False)
    finally:
        architecture_module.PROJECT_MAP_PATH = original
    assert any(item.check_id.endswith("MAP-004") for item in violations)
